// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7JdZ8FG71M9Syzp1VEDp78WDUjQ4uwEM',
    appId: '1:616236847375:web:your_web_app_id',
    messagingSenderId: '616236847375',
    projectId: 'magicbook-1db76',
    authDomain: 'magicbook-1db76.firebaseapp.com',
    storageBucket: 'magicbook-1db76.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7JdZ8FG71M9Syzp1VEDp78WDUjQ4uwEM',
    appId: '1:616236847375:android:a0b1c895f434454645ee7a',
    messagingSenderId: '616236847375',
    projectId: 'magicbook-1db76',
    storageBucket: 'magicbook-1db76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7JdZ8FG71M9Syzp1VEDp78WDUjQ4uwEM',
    appId: '1:616236847375:ios:your_ios_app_id',
    messagingSenderId: '616236847375',
    projectId: 'magicbook-1db76',
    storageBucket: 'magicbook-1db76.firebasestorage.app',
    iosBundleId: 'com.example.magicbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7JdZ8FG71M9Syzp1VEDp78WDUjQ4uwEM',
    appId: '1:616236847375:ios:your_macos_app_id',
    messagingSenderId: '616236847375',
    projectId: 'magicbook-1db76',
    storageBucket: 'magicbook-1db76.firebasestorage.app',
    iosBundleId: 'com.example.magicbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7JdZ8FG71M9Syzp1VEDp78WDUjQ4uwEM',
    appId: '1:616236847375:web:your_windows_app_id',
    messagingSenderId: '616236847375',
    projectId: 'magicbook-1db76',
    authDomain: 'magicbook-1db76.firebaseapp.com',
    storageBucket: 'magicbook-1db76.firebasestorage.app',
  );
}